title: <p align="center"> M Somasekhara Reddy </p>
logo: /assets/img/Photo_1.jpg

description:
  
  <br>   
    Total of 7 yrs. Experience in Verification and Validation in Avionics Domain.
    Good understanding of Black Box and White Box Testing methodologies.
    Good knowledge in Embedded C.
    Good Working Experience in Python based Test Scripts.
    Good Experience in Requirement Based Testing and Model Based Testing.
    Good Experience in verification and validation of MATLAB, SCADE models.
    Good Experience in to use Code Composer Studio debugger tool for Manual Testing.
    Good Experience in to use LDRA and RTRT tools for generate SCA Report and able 
    to understand the SCA gaps.
    Good Experience in verification and validation of HSIT.
    Good Experience in System Testing Report Analysis.
    Thorough understanding of Software Development Life Cycle (V-Model).
  <br>
  </p>



theme: jekyll-theme-minimal
