title: Somasekhar
logo: /assets/img/logo.png

description:
  <br>  
  I'm working on Data Science, Machine learning & NLP related problems.
  Worked with HCL for 3.10 years .
  Working with HCL for 3.5 years.
  <br>
